#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# app_lucky:
#    path: /lucky
#    controller: App\Controller\LuckyController::index

# app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number
